name: squads
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.0
  get_it: ^7.6.0
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  http: ^1.1.2
  appinio_swiper: ^2.1.0
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  #bloc unit test
  bloc_test: ^9.0.3
  mockito: ^5.0.0
  tuple: ^2.0.2
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true

flutter_gen:
  assets:
    enabled: true
    outputs:
      class_name: Assets
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true